#ifndef CONSTANTS_INCLUDED
#define CONSTANTS_INCLUDED

#define DIMENSIONS 2

#define MAX_LINELENGTH 50
#define MIN_BOARD_SIZE 3
#define MAX_BOARD_SIZE 100

// UI Constants
#define CURSOR_COLOUR 1

#define ROW_HEIGHT 2
#define COLUMN_WIDTH 6

#endif
