#ifndef CONSTANTS_INCLUDED
#define CONSTANTS_INCLUDED

#define DIMENSIONS 2

#define MAX_LINELENGTH 50
#define MIN_BOARD_SIZE 3
#define MAX_BOARD_SIZE 100

#define SPLASH_GAME_START 0
#define SPLASH_X_WON 1
#define SPLASH_O_WON 2
#define SPLASH_GAME_DRAWN 3

// UI Constants
#define CURSOR_COLOUR 1

#define ROW_HEIGHT 2
#define COLUMN_WIDTH 6

#endif
